server:
  port: 7001

spring:
  application:
    name: Euk1Server

eureka:
  client:
    #是否将自己注册到Eureka Server,默认为true，由于当前就是server，故而设置成false，表明该服务不会向eureka注册自己的信息
    register-with-eureka: true
    #是否从eureka server获取注册信息，由于单节点，不需要同步其他节点数据，用false
    fetch-registry: true
    #设置服务注册中心的URL，用于client和server端交流
    service-url:
#      defaultZone: http://192.168.1.252:7001/eureka/,http://192.168.1.252:7002/eureka/
      defaultZone: http://euk1.com:7001/eureka/,http://euk2.com:7002/eureka/
  instance:
    hostname: euk1.com
