server:
  port: 7000

spring:
  profiles:
    active: default,euk2
  #zipkin
  zipkin:
    base-url: http://localhost:9411/
    #采样比例1秒
  sleuth:
    sampler:
      rate: 1

eureka:
  instance:
    appname: Eureka-Server
    #    prefer-ip-address: true
    prefer-ip-address: false